name: "tagged-release"

on:
  push:
    branches:
      - deb-package

jobs:
  tagged-release:
    name: "ReleaseBuild"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        go_version: ['1.22']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
    
    - name: Install GoReleaser
      run: |
        go install github.com/goreleaser/goreleaser@latest
      env:
        PATH: ${{ runner.toolsDir }}/go/$${{ matrix.go_version }}/x64/bin:$${PATH}

    - name: "Build and Release"
      run: |
        goreleaser release --snapshot --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

